#!/bin/sh
cd ~
rm ./vncam.sh
echo "0">addtime
chmod 777 addtime
wget https://github.com/kyemperor/ky_script/raw/master/alexamaster/vncam.sh
sudo sh vncam.sh
wget https://github.com/kyemperor/ky_script/raw/master/alexamaster/mon.sh
chmod a+x mon.sh
echo '0 4 * * * /sbin/reboot
*/3 * * * * /root/mon.sh'>>/var/spool/cron/crontabs/root
grep -r 'Master'
echo "good!"
#reboot
sleep 5
reboot
